(() => {
  const atlas = JSON.parse(document.getElementById("atlas-data").textContent);
  const images = JSON.parse(document.getElementById("atlas-images").textContent);
  const element = id => document.getElementById(id);
  const colors = ["#67e8bc", "#8bc5ff", "#f2c875", "#ef94b6", "#c0a4ff", "#76d7e3", "#eeb39a", "#d6e784"];
  const canvas = element("panorama");
  const context = canvas.getContext("2d");
  const state = {clip: atlas.clips.find(clip => clip.view_ids.length) || atlas.clips[0], view: 0,
    yaw: 0, pitch: 0, fov: 65, roll: 0, pixels: null, width: 0, height: 0, pending: false, load: 0};
  const text = (tag, value, className) => {
    const node = document.createElement(tag);
    node.textContent = value;
    if (className) node.className = className;
    return node;
  };
  const views = () => state.clip.view_ids.map(id => atlas.views.find(view => view.view_id === id));
  const seconds = value => `${Math.floor(value / 60)}:${String(Math.floor(value % 60)).padStart(2, "0")}`;
  for (const [count, label] of [[atlas.summary.clips, "original recordings"], [atlas.summary.review_views, "retained review views"],
    [atlas.summary.gps_fixes.toLocaleString(), "timestamped GPS fixes"], [seconds(atlas.summary.duration_s), "captured video"]]) {
    const card = text("div", "", "stat");
    card.append(text("strong", count), text("span", label));
    element("stats").append(card);
  }
  for (const clip of atlas.clips) {
    const option = text("option", `${clip.source_name} · ${clip.view_ids.length} views`);
    option.value = clip.capture_id;
    element("clip").append(option);
  }
  for (const limitation of atlas.limitations) element("limitations").append(text("li", limitation));
  element("snapshot").textContent = atlas.atlas_id;

  function readiness() {
    const rows = [
      ["Model registration: not established", "No condo transform, terrain surface or architectural correction is generated by this atlas."],
      ["Projection: review only", "Vendor stitching or a validated raw-fisheye path is still required before calibrated reconstruction."],
      ["Missing declared files", `${atlas.summary.missing_derivatives} entries from the supplied manifest are absent; no replacement views were fabricated.`],
      ["GPS-to-view alignment", `${atlas.summary.located_views}/${atlas.summary.review_views} review views have a location candidate. Unverified clocks remain tentative.`],
      ["Track continuity", `${atlas.summary.track_breaks} telemetry breaks / jumps. They remain separate segments, never a smoothed invented path.`],
      ["Next reconstruction packet", "Choose a continuous facade/approach from these views; use denser original frames and held-out timestamps. GPS can supply a coarse prior, not accurate camera poses."],
    ];
    for (const clip of atlas.clips.filter(clip => clip.clock_diagnostic.status === "no_time_overlap")) {
      rows.unshift(["Clock mismatch: " + clip.source_name,
        `First GPS fix is ${clip.clock_diagnostic.first_fix_minus_container_start_s.toFixed(2)} seconds after the container start. No temporal overlap: its views stay unplaced. No automatic clock correction was applied.`]);
    }
    for (const [heading, body] of rows) {
      const row = text("div", "", "readiness-row");
      row.append(text("strong", heading), text("span", body));
      element("readiness").append(row);
    }
  }

  function drawMap() {
    const map = element("map");
    map.replaceChildren();
    const points = atlas.clips.flatMap(clip => clip.segments.flat());
    const frame = CaptureAtlasMath.mapFrame(points);
    if (!frame) return;
    const svg = (tag, attributes) => {
      const node = document.createElementNS("http://www.w3.org/2000/svg", tag);
      for (const [key, value] of Object.entries(attributes)) node.setAttribute(key, String(value));
      map.append(node);
      return node;
    };
    for (let horizontal = 35; horizontal <= 565; horizontal += 53) svg("line", {x1:horizontal,y1:25,x2:horizontal,y2:435,stroke:"#1b303d", "stroke-width":1});
    for (let vertical = 25; vertical <= 435; vertical += 41) svg("line", {x1:35,y1:vertical,x2:565,y2:vertical,stroke:"#1b303d", "stroke-width":1});
    atlas.clips.forEach((clip, clipIndex) => {
      for (const segment of clip.segments) {
        const positions = segment.map(point => frame.project(point));
        const opacity = clip.capture_id === state.clip.capture_id ? 1 : 0.33;
        if (positions.length === 1) {
          svg("circle", {cx:positions[0].horizontal,cy:positions[0].vertical,r:2,fill:colors[clipIndex],opacity});
        } else {
          svg("polyline", {points:positions.map(point => `${point.horizontal},${point.vertical}`).join(" "),
            fill:"none",stroke:colors[clipIndex],"stroke-width":clip.capture_id === state.clip.capture_id ? 3 : 1.5,opacity});
        }
      }
    });
    atlas.views.forEach((view, index) => {
      if (!view.location) return;
      const position = frame.project(view.location);
      const selected = views()[state.view]?.view_id === view.view_id;
      const circle = svg("circle", {cx:position.horizontal,cy:position.vertical,r:selected ? 10 : 6,
        fill:selected ? "#fff" : colors[atlas.clips.findIndex(clip => clip.capture_id === view.capture_id)],
        stroke:"#0b1823","stroke-width":2,tabindex:0,role:"button","aria-label":`Viewpoint ${index + 1}`});
      const choose = () => {
        state.clip = atlas.clips.find(clip => clip.capture_id === view.capture_id);
        state.view = state.clip.view_ids.indexOf(view.view_id);
        update();
      };
      circle.addEventListener("click", choose);
      circle.addEventListener("keydown", event => {
        if (event.key === "Enter" || event.key === " ") {event.preventDefault(); choose();}
      });
      if (selected) {
        const label = svg("text", {x:position.horizontal+13,y:position.vertical-10,fill:"#fff","font-size":13});
        label.textContent = String(index + 1);
      }
    });
    const scaleMetres = 10 ** Math.floor(Math.log10(100 / frame.scale));
    svg("line", {x1:35,y1:437,x2:35+scaleMetres*frame.scale,y2:437,stroke:"#a4bdce","stroke-width":3});
    svg("text", {x:35,y:425,fill:"#a4bdce","font-size":11}).textContent = `${scaleMetres} m · GPS display frame`;
  }

  function render() {
    state.pending = false;
    if (!state.pixels) return;
    const output = context.createImageData(canvas.width, canvas.height);
    for (let vertical = 0; vertical < canvas.height; vertical++) {
      for (let horizontal = 0; horizontal < canvas.width; horizontal++) {
        const uv = CaptureAtlasMath.projectPixel(horizontal, vertical, canvas.width, canvas.height,
          state.yaw, state.pitch, state.fov, state.roll);
        const sourceX = Math.min(state.width - 1, Math.floor(uv.u * state.width));
        const sourceY = Math.min(state.height - 1, Math.floor(uv.v * state.height));
        const sourceOffset = (sourceY * state.width + sourceX) * 4;
        const offset = (vertical * canvas.width + horizontal) * 4;
        output.data[offset] = state.pixels[sourceOffset];
        output.data[offset + 1] = state.pixels[sourceOffset + 1];
        output.data[offset + 2] = state.pixels[sourceOffset + 2];
        output.data[offset + 3] = 255;
      }
    }
    context.putImageData(output, 0, 0);
  }
  function scheduleRender() {
    if (!state.pending) {state.pending = true; requestAnimationFrame(render);}
  }
  function loadImage(view) {
    const loadId = ++state.load;
    state.pixels = null;
    context.clearRect(0, 0, canvas.width, canvas.height);
    if (!view) return;
    const image = new Image();
    image.onload = () => {
      if (loadId !== state.load) return;
      try {
        const source = document.createElement("canvas");
        source.width = image.naturalWidth;
        source.height = image.naturalHeight;
        const sourceContext = source.getContext("2d", {willReadFrequently:true});
        sourceContext.drawImage(image, 0, 0);
        state.width = source.width;
        state.height = source.height;
        state.pixels = sourceContext.getImageData(0, 0, source.width, source.height).data;
        element("render-status").textContent = "Drag / arrow keys to look · scroll or +/− to zoom · software-rendered only on interaction · direction is not compass calibrated.";
        scheduleRender();
      } catch {
        element("render-status").textContent = "Panorama rendering is unavailable. The full source image remains available below.";
      }
    };
    image.onerror = () => {
      if (loadId === state.load) element("render-status").textContent = "Review image failed to load; no replacement is shown.";
    };
    image.src = images[view.file];
  }

  function update() {
    const selectedViews = views();
    const view = selectedViews[state.view];
    element("clip").value = state.clip.capture_id;
    element("clip-info").textContent = `${seconds(state.clip.duration_s)} video · ${state.clip.gps_count} GPS fixes · ${state.clip.segments.length} display segments\nClock: ${state.clip.clock.verified ? "operator verified" : "unverified container timestamp"}\nGPS horizontal accuracy: ${state.clip.accuracy_known ? "recorded; inspect JSON" : "unknown"}`;
    if (state.clip.clock_diagnostic.status === "no_time_overlap") element("clip-info").textContent += `\nClock mismatch: first GPS fix is +${state.clip.clock_diagnostic.first_fix_minus_container_start_s.toFixed(2)} s from container start. Images are NOT placed on this track.`;
    element("view-title").textContent = view ? `View ${atlas.views.indexOf(view) + 1} · ${seconds(view.source_time_s)}` : "No review images";
    element("view-count").textContent = `${selectedViews.length ? state.view+1 : 0} / ${selectedViews.length} in clip`;
    element("previous").disabled = !view || state.view === 0;
    element("next").disabled = !view || state.view === selectedViews.length - 1;
    element("timeline").max = Math.max(0, selectedViews.length-1);
    element("timeline").value = state.view;
    element("timeline").disabled = selectedViews.length < 2;
    element("empty").hidden = Boolean(view);
    element("view-info").textContent = view ? `${state.clip.source_name}\n${view.location ? "Tentative GPS location" : "No GPS location at this approximate frame time"} · source seek ≈ ${view.source_time_s.toFixed(1)} s · no camera pose solved.` : "The raw recording is retained. This packet contains no review derivative for it.";
    if (view?.location?.alignment_verified) element("view-info").textContent = `${state.clip.source_name}\nClock-verified GPS candidate; positional accuracy is not certified · source seek ≈ ${view.source_time_s.toFixed(1)} s.`;
    element("source-image").hidden = !view;
    if (view) element("source-image").src = images[view.file];
    else element("source-image").removeAttribute("src");
    element("provenance").textContent = view ? JSON.stringify({view, source_sha256:state.clip.source_sha256, clock:state.clip.clock}, null, 2) : "";
    element("filmstrip").replaceChildren();
    atlas.views.forEach((candidate, index) => {
      const button = text("button", "");
      button.setAttribute("aria-pressed", String(candidate.view_id === view?.view_id));
      button.setAttribute("aria-label", `Select viewpoint ${index+1}`);
      const thumbnail = new Image();
      thumbnail.src = images[candidate.file];
      thumbnail.alt = `Provisional panorama ${index+1}`;
      thumbnail.loading = "lazy";
      const clipIndex = atlas.clips.findIndex(clip => clip.capture_id === candidate.capture_id);
      button.append(thumbnail, text("span", `View ${index+1} · Clip ${clipIndex+1} · ${seconds(candidate.source_time_s)}`));
      button.onclick = () => {state.clip = atlas.clips[clipIndex]; state.view = state.clip.view_ids.indexOf(candidate.view_id); update();};
      element("filmstrip").append(button);
    });
    drawMap();
    loadImage(view);
  }
  element("clip").onchange = event => {state.clip = atlas.clips.find(clip => clip.capture_id === event.target.value); state.view = 0; update();};
  element("previous").onclick = () => {state.view--; update();};
  element("next").onclick = () => {state.view++; update();};
  element("timeline").oninput = event => {state.view = Number(event.target.value); update();};
  element("reset").onclick = () => {Object.assign(state, {yaw:0,pitch:0,fov:65,roll:0}); scheduleRender();};
  element("flip").onclick = () => {state.roll = state.roll ? 0 : Math.PI; scheduleRender();};
  let pointer = null;
  canvas.onpointerdown = event => {pointer = {id:event.pointerId,horizontal:event.clientX,vertical:event.clientY}; canvas.setPointerCapture(event.pointerId);};
  canvas.onpointermove = event => {
    if (!pointer || pointer.id !== event.pointerId) return;
    state.yaw -= (event.clientX - pointer.horizontal) * .004;
    state.pitch = Math.max(-1.5, Math.min(1.5, state.pitch + (event.clientY - pointer.vertical) * .004));
    pointer.horizontal = event.clientX; pointer.vertical = event.clientY;
    scheduleRender();
  };
  canvas.onpointerup = canvas.onpointercancel = canvas.onlostpointercapture = () => {pointer = null;};
  canvas.addEventListener("wheel", event => {event.preventDefault(); state.fov = Math.max(35, Math.min(100, state.fov + event.deltaY*.03)); scheduleRender();}, {passive:false});
  canvas.onkeydown = event => {
    if (!["ArrowLeft","ArrowRight","ArrowUp","ArrowDown","+","=","-"].includes(event.key)) return;
    event.preventDefault();
    if (event.key === "ArrowLeft") state.yaw -= .12;
    if (event.key === "ArrowRight") state.yaw += .12;
    if (event.key === "ArrowUp") state.pitch = Math.min(1.5, state.pitch+.12);
    if (event.key === "ArrowDown") state.pitch = Math.max(-1.5, state.pitch-.12);
    if (event.key === "+" || event.key === "=") state.fov = Math.max(35,state.fov-5);
    if (event.key === "-") state.fov = Math.min(100,state.fov+5);
    scheduleRender();
  };
  readiness();
  update();
})();
