[Unit]
StartLimitIntervalSec=10min
StartLimitBurst=3

[Service]
CPUAccounting=yes
CPUQuota=400%
CPUQuotaPeriodSec=10ms
CPUWeight=20
Nice=10
MemoryAccounting=yes
MemoryHigh=32G
MemoryMax=48G
MemorySwapMax=8G
TasksAccounting=yes
TasksMax=512
KillMode=control-group
TimeoutStopSec=45s
Restart=on-failure
RestartSec=30s
